### ISSUE TITLE
Volts should be reported to at least 1 decimal place, preferably 2

### ISSUE THREAD

**Issue by DefueBugs** [Zren/plasma-applet-sysmonitordash#12]
Currently voltages are reported as zero decimal places (whole numbers). This is not useful for voltage levels reported for Vcore, VDIMM and other related measurements. For (a real life) example, a Vcore of 0.86 volts and VDIMM of 1.35 volts both get reported as 1V.

**Comment by Zren** [comment]
Is 3 decimal places okay? Past that, the numbers were all zeros for me.

![2019-03-02___09-51-03](https://user-images.githubusercontent.com/416367/53683669-8fce3c80-3cd1-11e9-98be-ac6943d13d16.png)

What other presets should apply to *all* voltage graphs?

**Comment by Zren** [comment]
Both `sensors` and the gnome widget use 2 digits, so I'll need to round to it.

https://github.com/UshakovVasilii/gnome-shell-extension-freon/blob/master/freon%40UshakovVasilii_Github.yahoo.com/extension.js#L413

**Comment by DefueBugs** [comment]
2 digits is plenty.
