### ISSUE TITLE
sensors displays sensor information, but monitor-dash does not.

### ISSUE THREAD

**Issue by iCodeSometime** [Zren/plasma-applet-sysmonitordash#15]
First of all, thanks for making this beautiful widget. Most of the stats display fine on startup

The only graphs Im having trouble with is the temperature and fan speed graphs. lm-sensor is installed, and the command sensors correctly returns the various temps, however the graphs are totally missing. I appreciate any assistance you're able to give.

https://i.imgur.com/uVXrZte.jpg

**Comment by iCodeSometime** [comment]
I was able to figure this one out. i've used Linux a good bit, but mostly command line. Some additional info in the readme about how to launch and configure it might be helpful

**Comment by Zren** [comment]
Holy 32 cores batman. Looks like I found the upper limit of how many cores I can reasonably show in the overlay legend. I've thought about replacing it with a grid of single core graphs like the windows task manager once we get to 16 cores. 32 cores really needs that as a 100px tall graph divided by 32 cores is just 3px per core. 16 cores is 6px per core. So I think I'll definitely switch by 16 cores.

Yeah, I think I'll add a "configure sensors" button to the right column that'll open the widget's config to help guide users on their first install. There's hundreds of sensors to choose from so it kinda needs the user to manually select them. The disks + networks is fairly easy to parse, but there's tons of temps + fans.

**Comment by iCodeSometime** [comment]
well, it's 16 with multithreading. Thank you for the prompt response.

Since I have you here, do you know of any easy way to determine what each sensor id is related to?

**Comment by Zren** [comment]
Does it mention what they are in the output of `sensors`? I had to read the lm-sensors config for my motherboard to understand mine:

https://github.com/lm-sensors/lm-sensors/blob/70f7e0848410b9ca4dde7abff669bbbecbf137e0/configs/Gigabyte/GA-990FXA-UD3.conf
